### ISSUE TITLE
send() not printing out to console

### ISSUE THREAD

**Issue by harhur** [Ge0rg3/requests-ip-rotator#14]
Hello,

I was tinkering around with `send(self, request, ...)` in `ip_rotator.py` and noticed that print statements in the method will not show up. But, print statements in the module's other methods like `start()` will show in console. 

I assume `send(self, request, ...)` is being used under the hood? If this is the case, how come the print statements don't show up? Is there any other way way to view details about the `request` parameter?

Thanks

**Comment by Ge0rg3** [comment]
Hi, currently there is no logging within the send() method -- if you want to view the request parameter, I would recommend creating a wrapper class that inherits from ApiGateway, that logs `request` and then calls the ApiGateway's send() method via super 😄

**Comment by harhur** [comment]
I see, I will try that out and post my update in this thread. Thanks!

**Comment by harhur** [comment]
Follow-up, I am trying to use your library to proxy requests to Yahoo Finance. However, I get rate limited after ~50 or so requests and need to wait a couple minutes. Interestingly, after this happens even *other devices* on my home wifi are unable to load the request until a wait a bit.

So I am curious, do you have any idea as to how Yahoo Finance is able to rate limit me even if I am using this library? Does the original client IP -- which would be my home wifi IP -- not get changed in each request? If so, do you have any suggestions for how I can modify your library to do this?

Thanks a ton @Ge0rg3

**Comment by Ge0rg3** [comment]
Hey, yeah in the old version of the library (a few weeks ago), the X-Forwarded-For header was revealing the true client IP each time but in the latest version it's randomized too. Which version of the library are you running?

**Comment by harhur** [comment]
Got it, I noticed that in the changelogs and upgraded to v1.0.10 as a result. So just to confirm, putting print() statements in your code should not show up, right? For example, in line 67 in your `send()` method. I would need to do what you suggested above with the wrapper?

**Comment by Ge0rg3** [comment]
If you add print statements yourself then for sure they would show up, but would require making changes to the library. I would recommend doing something like this:
```py
class LoggingGateway(ApiGateway):
    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        print(request)
        return super().send(request, stream, timeout, verify, cert, proxies)
```
...and then using `LoggingGateway` as a replacement for `ApiGateway`.
Please let me know if there are any issues with this?

**Comment by harhur** [comment]
Thanks for the code snippet. I think this is what I was mainly wondering about; it doesn't look like `send()` is actually called in the library, because the above snippet doesn't print out anything. To demonstrate, I have the following in my codebase -- note that this is before I added in the snippet above:

`ip_rotator.py (the library)`
```
class ApiGateway(rq.adapters.HTTPAdapter):
    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        # Get random endpoint
        endpoint = choice(self.endpoints)
        print(endpoint) # this SHOULD print something, but there is no output 
```

`my_file.py (file in my project)`
```
TEST_URL = 'http://reddit.com/'
self.gateway = ApiGateway(TEST_URL,
                            regions=EXTRA_REGIONS,
                            access_key_id=AWS_ACCESS_KEY_ID,
                            access_key_secret=AWS_SECRET_KEY)
self.gateway.start(force=True)

self.session = requests.Session()
self.session.mount(TEST_URL, self.gateway)

# Random user agent generator (you can ignore this)
self.user_agent_rotator = UserAgent(limit=1000)
user_agent = self.user_agent_rotator.get_random_user_agent()
self.session.headers.update({'User-agent': user_agent})

# Get the response
response = self.session.get(endpoint)
return response.json()
```

With or without the wrapper snippet above, there is no output in `send()` -- regardless of where I put print() method. 

Now of course, if I were to explicitly call `send()` in `my_file.py`, I can see the print statements. But I wasn't sure if this would defeat the purpose of some under the hood magic that this library did :)

**Comment by Ge0rg3** [comment]
Hi, when running something similar locally I do indeed see debug logs placed within the send() function. Maybe you have some dependency confusion -- i.e. intending to import your local ip_rotator.py but are instead still importing requests_ip_rotator? The send() method is called on each request.

**Comment by harhur** [comment]
I see, this is definitely possible and I investigated further. However, I am indeed using the local ip_rotator.py (with the code changes), and I can confirm this via the below code:

`ip_rotator.py`
```
def start(self, force=False, endpoints=[]):
    # Otherwise, start/locate new endpoints
    print(f"THIS IS MY CHANGE -- Starting API gateway{'s' if len(self.regions) > 1 else ''} in {len(self.regions)} regions.") # this print statement changes, which is good
...

def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
    print('IN SEND') # this does NOT show up
...
```

So, print statements show up in the `start` method but not the `send` method... strange.

I debugged this further and it looks like doing `session.get(endpoint)` goes straight to `sessions.py`, from which `sessions.py` will directly make the request. Could this bug be related to the other libraries' versions, like `sessions` or `boto3`? Or, does anything with how I am using `requests_ip_rotator` look off? 

If you're comfortable with it, we could also live-debug this over a call while I share my screen -- but I completely understand if you'd prefer we keep this conversation in this thread :)

**Comment by Ge0rg3** [comment]
Sure, add me on Discord George#1234
sessions.py uses its' own send method, which calls `adapter = self.get_adapter(url=request.url)`, and later `r = adapter.send(request, **kwargs)` meaning that the adapter's send method is ultimately called.

**Comment by harhur** [comment]
Thanks! I sent you a friend request; my username is `targ#8444`.

**Comment by Ge0rg3** [comment]
Hey @harhur, did you solve your issue?

**Comment by harhur** [comment]
Hey, not quite yet, I've been traveling the past few days and haven't had a
chance to message you on Discord yet. I'll message you soon though! Please
feel free to close this issue out now

**Comment by Ge0rg3** [comment]
Issue was due to separate URLs being used when mounting the session, and sending the request 👍

**Comment by harhur** [comment]
Resolved -- for anyone else with a similar issue, make sure that the domain that is mounted in `session.mount(URL)` is that of the endpoint you are trying to make a request to.
