### ISSUE TITLE
Sending custom web schemes

### ISSUE THREAD

**Issue by nre226** [Ge0rg3/requests-ip-rotator#15]
So far this has been an awesome repo. Unfortunately, I am trying to do something perhaps a little outside of the scope and wanted to see if there was any guidance anyone could supply. Instead of web addresses like https://www.google.com I need to access something more similar to https://variable.google.com where variable is going to be a multitude of different strings. Is there any way to set up a gateway that can adjust to a multitude of base urls or does it have to be completely static?

**Comment by Ge0rg3** [comment]
Hi,
In the current version of the lib wildcard subdomains are not supported, but it does look like API Gateway now supports them. I'll consider this integration in the next version of the lib 😄

**Comment by nre226** [comment]
That would be fantastic. Thank you!

**Comment by Ge0rg3** [comment]
Hi @nre226, after some further research it looks like this is not possible via the version of ApiGateway we are using (HTTP), but only in their other offering (Rest)😢

**Comment by sachinjsd** [comment]
Is this possible now?

**Comment by Ge0rg3** [comment]
Hi @sachinjsd, sadly this is not possible under the current implementation.
