### ISSUE TITLE
how to check if its working

### ISSUE THREAD

**Issue by AlexWayne20** [Ge0rg3/requests-ip-rotator#20]
hi,
im running the request ip rotator in a while infinite loop. But i dont know if its really working, is it sending requests with different ip, how can i check that? im asking because i see in the terminal "IP Rotate API' (0 new)"

"Starting API gateways in 17 regions.
Using 17 endpoints with name 'https://www.google.com - IP Rotate API' (0 new).
running #3 - Status code: 200 - Host: 2000qnx4dm5b6.execute-api.us-east-1.amazonaws.com - Request headers X-My-X-Forwarded-For: XX.XXX.XXX.XX" 

why do i see 0 new?

**Comment by sherif-med** [comment]
If you want to check your requests headers, you can use [link1](https://www.toptal.com/developers/postbin) or [link2](https://webhook.site/), by sending requests through the gateway to one of these.
The issue is that one gets to know my real ip and the other didn't.

**Comment by Ge0rg3** [comment]
@sherif-med have you upgraded to the latest version of requests-ip-rotator? In an older version, the X-Forwarded-For header is not randomized by default, and webhook.site trusts X-Forwarded-For as the true IP.

**Comment by sherif-med** [comment]
Yes I am using v.1.0.10
If you try to visualize request headers using [link](https://webhook.site/), you can see that your real ip is still showing.

**Comment by Ge0rg3** [comment]
@sherif-med please share with me the exact code you're running to use the library -- it is working fine for me on version v1.0.10 without revealing real IP 😄

**Comment by sherif-med** [comment]
I was missing the "X-my-Forwarded-.." header when using curl. That's it. It's working fine.
