### ISSUE TITLE
REST API pricing per Region

### ISSUE THREAD

**Issue by L0k156** [Ge0rg3/requests-ip-rotator#23]
I have looked into the REST API pricing, the prices seem to be between 3$ and 4$ for <1mil requests per REGION.
When starting the gateway it starts API gateways in 10 regions, with each start, does that mean I would have to pay 3/4$ for all regions used to send requests, in a single month? 

TO save my costs, would I need to use the same region each time starting the API Gateway to limit my costs to only one region 3/4$.
Something like this:

```
gateway = ApiGateway("https://site.com", regions=["eu-west-1"])
gateway.start()
```

This would use only the EU west region and I would pay only for the region used, not for multiple regions in case i dont specify the regions parameter?

**Comment by Ge0rg3** [comment]
Hi @L0k156, as per my understanding, AWS provides the first million requests for free per region, and as such it's cheaper to use a wide range of regions instead of only a few (i.e., using 10 regions would allow you 10 million free requests instead of just 1 million).

**Comment by L0k156** [comment]
@Ge0rg3 thanks for the answer, just to make sure we are on the same page;
as I understood (https://aws.amazon.com/api-gateway/?did=ft_card&trk=ft_card) from the link "1 million API calls received free per month for 12 months with the AWS Free Tier", the 1 mil free requests are only for first 12 months.

So my question would be, after the free trial period, whether using only one region as indicated here;
```
gateway = ApiGateway("https://site.com", regions=["eu-west-1"])
gateway.start()
```
would make sure my ie. 10k monthly requests are not randomized across 10 or 20 of different regions and I end up paying 30/60$? But only for one region.

**Comment by Ge0rg3** [comment]
Hi,
Sorry for the very late reply! Yes, this is the case, you can put just the one region and all your requests would be in it. So, if you were trying to stay within your free tier, you could send the first 1mil requests in your first region, then iterate through to another, etc.
If you don't include a region, as its random there is a slight chance one may occur more than another so you may go a little over your limit if sending millions of requests, but it wouldn't be by much.
Hope this helps 😄
