### ISSUE TITLE
Unable to add parameters to request

### ISSUE THREAD

**Issue by tillea** [Ge0rg3/requests-ip-rotator#26]
Hi,
I want to download URLs with certain parameters.  For instance when trying to download

    https://webtv.feratel.com/webtv/?cam=3175&t=12&design=v4

I can do with plan request

    params = dict()
    params['cam']="3175
    params['t']="12"
    params['design']="v4"
    response = requests.get('https://webtv.feratel.com/webtv/', params=params)

It does not work when simply specifying the full URL and leaving out `params`.

Unfortunately for the `get` method of the session in `requests-ip-rotator` there is no `params` parameter and I guess this is the reason why trying to fetch the link above fails.

Kind regards
      Andreas.

**Comment by abdou4a** [comment]
try to use [urllib.parse.urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode)
`
import urllib.parse
params = urllib.parse.urlencode(params)
url = "https://webtv.feratel.com/webtv/?%s" % params
`

**Comment by abdou4a** [comment]
try to use [urllib.parse.urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode)

```
import urllib.parse
params = urllib.parse.urlencode(params)
url = "https://webtv.feratel.com/webtv/?%s" % params
```

**Comment by tillea** [comment]
Am Sun, Feb 06, 2022 at 04:11:08AM -0800 schrieb abdou4a:
> try to use [urllib.parse.urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode)
> 
> ```
> import urllib.parse
> params = urllib.parse.urlencode(params)
> url = "https://webtv.feratel.com/webtv/?%s" % params
> ```

Thanks for the hint.  I tried this but the resulting string does not look different from what I tried and so the website keeps on returning 404.

Kind regards, Andreas.

**Comment by Ge0rg3** [comment]
Hi, I have retested this on the latest version and believe it's fixed, as the `params` parameter can now be used 😄
