### ISSUE TITLE
Shut down gateway after keyboard keyboard interrupt?

### ISSUE THREAD

**Issue by JanEricNitschke** [Ge0rg3/requests-ip-rotator#28]
Hi, i am new to this. What happens if i stop a script via keyboard interrupt (it because it errors) before `gateway.shutdown()` is reached.
Is there a way to shut it down afterwards? Either via a script or the AWS website?

**Comment by Ge0rg3** [comment]
Hi! You can shutdown any site by doing:
```python
from requests_ip_rotator import ApiGateway
gateway = ApiGateway("https://site.com")
gateway.shutdown()
```

Or by re-running your program and not "ctrl-c"ing 😄
