### ISSUE TITLE
Hi there everyone. Why it is necessary to shutdown api gateway???

### ISSUE THREAD

**Issue by amanrawat121** [Ge0rg3/requests-ip-rotator#40]
Hi @Ge0rg3 and all. I have a question that's bothering me for a long time. I want to know :
1. Why it is necessary to shut down api gateway. 
2. What if I don't do that?? 
3. Will I face charges for gateway used by someone else??

Please answer these questions to relax my mind.🙏🙏🙏

**Comment by Ge0rg3** [comment]
Hi,
AFAIK, there is no requirement to shut it down, and it will not charge you so long as no traffic passes through it.
If somebody else uses your gateway, then you will face charges. However, as the gateway URLs are very unique, it is hugely improbable for someone else to use it, so pretty safe!
I hope this helps?

**Comment by amanrawat121** [comment]
Thank you for your speedy reply. Now I get it. I'll mark this one closed
