### ISSUE TITLE
'ApiGateway' object has no attribute 'endpoints'

### ISSUE THREAD

**Issue by masdeval** [Ge0rg3/requests-ip-rotator#41]
Hi guys.

I just installed the solution and did all the configuration (AWS ID, Secret, etc). 

When I call session.get I get in error message "'ApiGateway' object has no attribute 'endpoints'"

I noticed looking at the code, there is no self.endpoints as required in the first line of method send:
`endpoint = choice(self.endpoints)`

How should I proceed?

**Comment by Ge0rg3** [comment]
Hi,
Did you run `gateway.start()`?
Thanks

**Comment by masdeval** [comment]
Now it worked.

Thank you!

**Comment by masdeval** [comment]
Could you help me in something else?

I am getting status code 421 -  "The client needs a new connection for this
request as the requested host name does not match
the Server Name Indication (SNI) in use for this
connection."

 I am starting the gateway as ApiGateway("https://cornershop.com") and all the subsequent calls are using the prefix https://cornershop.com

What am I doing wrong?
