### ISSUE TITLE
How to scrape google with amazon gateway  api 

### ISSUE THREAD

**Issue by muskansingh65553** [Ge0rg3/requests-ip-rotator#42]
I tried many things !! check many tutorials but didn't find any solution :( :( 
admin could you please guide me how to scrape google with amazon gateway api  in python?

Thank you

**Comment by muskansingh65553** [comment]
I made this after watching tutorial :- https://vqpbawduf1.execute-api.us-east-1.amazonaws.com/test

but how to use with python and google dynamic search query

**Comment by Ge0rg3** [comment]
Apologies, the Github issues section is not for site-specific issues, please raise something on Stackoverflow or similar 🙂
