### ISSUE TITLE
Monitoring AWS requests quota usage

### ISSUE THREAD

**Issue by vincenthawke** [Ge0rg3/requests-ip-rotator#5]
Sorry, this isn’t really an issue with the script, but it does affect it and I am sure others will benefit, if someone posts an answer here. 

I spent hours (not joking) going through Amazon's maze of a aws website. The closest I came to getting some kind of reporting was: `https://console.aws.amazon.com/cloudwatch/` but it makes no sense. I made several 10,000 requests on my zone since yesterday and I can’t find that number reported anywhere (I did select my zone). I plan to use it much more and would love to know, where I can actively monitor my free quota usage. 

They mention:
> If you are eligible for the AWS Free Tier and you use a AWS Free Tier offering, you can track your usage with the Top AWS Free Tier Services by Usage table on the dashboard of the Billing and Cost Management console

But I have no chart or table called `Top AWS Free Tier Services by Usage` in my Billing console. 

I ticked the box `Receive Free Tier Usage Alerts` in Billing Console -> Billing preferences and that is all that is there to opt-in, only alerts. Where is the usage?:) 

I also tried `AWS Cost Management`, and it is all empty... Maybe I need to wait, it does say `It can take up to 4 days for AWS Cost Explorer data to become available. Please try again soon.` It doesn't sound right though, cost, it should be usage or performance report of some kind. 
Thanks!

*** I found it!!! ***

It was under /cloudwatch all along, but getting the report to show anything useful was quite confusing.
Here is the link to my report for my zone: `https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#cw:dashboard=ApiGateway`

I got it by going to `https://console.aws.amazon.com/cloudwatch/` and then clicking `Metrics -> All metrics`. When hovering over the `Api Gateway` link, I got `view automatic dashboard` and that gave me something to start from. Still need to figure out how to sum it up by days, but this is the right place. 

https://i.imgur.com/D7H0l7v.png

It appears that the report is a bit behind, maybe a full day or 12 hours, it is definitely not updated live.

**Comment by Ge0rg3** [comment]
Hi, I see this was closed but I'll add something to the FAQ to avoid future confusion 😄 

AWS regions are so confusing and have messed me up for ages before!

**Comment by DjarDjar** [comment]
@vincenthawke I am having the same issue. I really kind find any type of some sort of a report for my usage. Could share if you have found anything?
