### ISSUE TITLE
How I can bypass cloudflare?

### ISSUE THREAD

**Issue by MsLolita** [Ge0rg3/requests-ip-rotator#51]
The site has Cloudflare protection to bypass it as I know I need to spoof tls fingerprint. How I can change tls fingerprint with code or in aws? Or mb there is another method to bypass it?

**Comment by luisvivasg** [comment]
I am having the same issue.  If I run it with IP, it works fine for few requests but when I use Amazon proxy it does not even allows one.

**Comment by george-photon** [comment]
Apologies, this issue is unrelated to the repo so will be closing. For bypassing cloudflare please refer to repos such as [cloudscraper](https://github.com/VeNoMouS/cloudscraper/), or use a service such as [SmartProxy](https://smartproxy.com/scraping/web).

**Comment by ashkaps** [comment]
Cloud scraper won’t actually work in its open source version.

**Comment by MsLolita** [comment]
> 

I guess for bypassing you can add tls fingeprint in future for this library. If it is possible
