### ISSUE TITLE
Error: Rotated IP failed (Exceeded 2 redirects.)

### ISSUE THREAD

**Issue by ashirsyed** [Ge0rg3/requests-ip-rotator#58]
I am trying to hit a website page with requests-ip-rotator but always get error even if I exceed the limit of redirects up to 100. If I hit the website from requests library or postman it works fine. But using this library, the new mapped API Gateway IP is created but it redirects to the original website page.

I even tried to fetch the redirected link and try to fetch from it but still in vain. 

import requests
from urllib.parse import urlparse
from requests_ip_rotator import ApiGateway
from fake_headers import Headers

def get_header():
    header = Headers(
        browser="chrome",  # Generate only Chrome UA
        os="win",  # Generate ony Windows platform
        headers=True  # generate misc headers
    )
    return header.generate()

aws_access_key_id = 'aws_access_key_id'
aws_secret_access_key = 'aws_secret_access_key'

src = 'https://www.ittefaqsay.com/product/kenwood-split-ac-kee-1253-e-comfort-plus/'

src_parsed = urlparse(src)
src_nopath = "%s://%s" % (src_parsed.scheme, src_parsed.netloc)

gateway = ApiGateway(src_nopath,                                           
                      regions=['eu-west-2'],                                             
                      access_key_id=f"{aws_access_key_id}",                                             
                      access_key_secret=f"{aws_secret_access_key}")                       
gateway.start(force=True)
session = requests.Session()
session.headers=get_header()
session.headers['User-Agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36'
session.headers.update({'Accept': '/'})
session.max_redirects = 2
#session.max_redirects = 100
#session.headers['User-Agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36'
session.mount(src_nopath, gateway)

r = None
try:
    r = session.get(src, stream=True, allow_redirects=True)
    redirect_url = r.headers['Location']
    print("this is redirected url",redirect_url)
    # now we can manually inspect and fix the redirect url if necessary and then follow it:
    r = session.get(redirect_url, allow_redirects=True)
    print(r.url)
    file_request_succeed = r.ok
    print("MSG:", file_request_succeed)
    if file_request_succeed:
        print('Rotated IP succeed',r)
except Exception as e:
    print(r.url) if r else print("FAILED!", r)
    print('Rotated IP failed (%s)' % str(e))

gateway.shutdown()

**Comment by Ge0rg3** [comment]
Hi @ashirsyed, thank you for the issue. Just checked and seems like this is due to how the site handles requests from AWS/mismatching hosts, and not an issue with the library. I hope you find a way to solve this issue - if you are looking for an alternative, I would recommend a provider such as SmartProxy or ScrapFly 🙂

**Comment by ashirsyed** [comment]
Thanks a lot. Will look into it.
