### ISSUE TITLE
AWS Costs

### ISSUE THREAD

**Issue by rexovas** [Ge0rg3/requests-ip-rotator#59]
Excellent package here, a true lifesaver.

Not really a library issue, but based on the README, I was expecting costs to be little or nothing, however - it seems that I've managed to rack up $40.00 of API Gateway costs this month alone.  I'm really not sure how this can be, I would expect my number of requests to be < 1,000,000.

Not a big deal, but was a bit surprised.  Any ideas why the costs are so high?

**Comment by Ge0rg3** [comment]
Hi @rexovas! When you were using the library, did you stick to one region only or did you spread across many? If you spread across, then you get the benefit of using the free tier in each separate region, otherwise you'll quickly use it up in just one.

**Comment by rexovas** [comment]
I spread across many, in fact - half of the costs are associated with “Other” regions

![0D14F41A-7D63-48D3-A646-245136CA4FA9](https://github.com/Ge0rg3/requests-ip-rotator/assets/33384036/1e244c7d-fdab-43ad-baed-bfb6ad8b1781)
![43C34891-0B75-48AF-9055-DE77FAD95B82](https://github.com/Ge0rg3/requests-ip-rotator/assets/33384036/d602ae91-6fab-4e0d-b62b-391c36ca1837)

**Comment by Ge0rg3** [comment]
Strange.. Please can you check your free tier status on the Billing Console->Free Tier page?

**Comment by rexovas** [comment]
Ah yep, this account is maybe 5-6 years old

<img width="1205" alt="Screenshot 2023-05-11 at 6 49 08 PM" src="https://github.com/Ge0rg3/requests-ip-rotator/assets/33384036/ece11e80-d250-42ce-99cf-2b2c626ed01f">

**Comment by Ge0rg3** [comment]
Ahh yep that would be it.. I should probably clarify the higher costs in the README 😊
