### ISSUE TITLE
'x_forwarded_for' is printing None for all requests

### ISSUE THREAD

**Issue by kelpapeksha** [Ge0rg3/requests-ip-rotator#62]
`try:
            response = session.get(search_url, headers=headers)
            x_forwarded_for = response.headers.get("X-Forwarded-For")
            # if x_forwarded_for:
            print(f"X-Forwarded-For: {x_forwarded_for}")
            print(f"URL: {search_url}, Status Code: {response.status_code}")
        except Exception as e:
            print(f"Error fetching URL {search_url}: {str(e)}")`

This is my code, for every request whether 200, 404 or 429, is getting print as **None**

**Comment by kelpapeksha** [comment]
@Ge0rg3 , how can i check if the ip rotation is happening, i am still getting 404, 429 errors.

**Comment by Ge0rg3** [comment]
Hey, usually I test using webhook.site, for example:
```py
import requests as rq
from requests_ip_rotator import ApiGateway

with ApiGateway("https://webhook.site") as gateway:
    s = rq.Session()
    s.mount("https://", gateway)

    # Replace with your unique webhook.site url
    webhook_url = "https://webhook.site/your-url"
    resp = s.get(webhook_url)
    print(resp.status_code)
```

Make sure you replace the webhook url with the correct unique URL that you can get from the site 😄
