### ISSUE TITLE
Keep One IP per request until it shutdown 

### ISSUE THREAD

**Issue by zmkaihan** [Ge0rg3/requests-ip-rotator#63]
I want this to rotate only once and keep that IP for requesting until it shuts down How can I achieve this? Any help will be really appreciated.

**Comment by Ge0rg3** [comment]
Hi @zmkaihan, this is not available through this library.
However, this is possible via AWS Lambda Functions! For example, if you create a lambda to perform the web/scraping task that you need, each time you hit the lambda you will get a different IP but all requests from within the lamdba invocation will have a consistent IP.
