### ISSUE TITLE
Returns 403 on EC2 but 200 Locally

### ISSUE THREAD

**Issue by sokffa** [Ge0rg3/requests-ip-rotator#64]
I am using this library as a proxy to scrape a website. When I test the setup locally, I receive a 200 OK response. However, when I run the same setup from an EC2 instance, I get a 403 Forbidden.

What could be the reasons behind the 403 Forbidden response on EC2, and how can I resolve it?

**Comment by Ge0rg3** [comment]
Hey @sokffa!

This is likely due to how you are setting the AWS access key and secret. In your local, is it set as an environment variable, that perhaps isn't set in the EC2?

In this library, you can either set the access key via env variables or explicitly pass them in the ApiGateway constructor - please see the usage example in the README for more info 😄 

Hopefully this helps.

**Comment by sokffa** [comment]
I'm setting it u

> Hey @sokffa!
> 
> This is likely due to how you are setting the AWS access key and secret. In your local, is it set as an environment variable, that perhaps isn't set in the EC2?
> 
> In this library, you can either set the access key via env variables or explicitly pass them in the ApiGateway constructor - please see the usage example in the README for more info 😄
> 
> Hopefully this helps.

Thank you for answering. I'm explicitly passing them in the constructor. It used to work before but now it stopped working on ec2  I'm guessing there has been some improvements to the security of the website that I'm scraping, but I can't figure out why it works locally

**Comment by Ge0rg3** [comment]
Hi!
Unfortunately it sounds like this might be an issue with the library implementation or the site itself, so I'm afraid I can't help much here. If you provide the scraping code that you have I'd be happy to take a look.

**Comment by rexovas** [comment]
This sounds like perhaps an IAM role issue.  It is not recommended to leverage aws secret keys / authentication_tokens on EC2 instances.  Instead, the IAM role attached to the EC2 instance should have permissions to leverage api gateway and any other required resources.  This is most likely the reason for your 403 errors, missing IAM role policies.

**Comment by Ge0rg3** [comment]
Hi @sokffa, did you get this resolved in the end? Feel free to reopen if there is still an issue
