### ISSUE TITLE
rotate ip for selenium

### ISSUE THREAD

**Issue by jun3599** [Ge0rg3/requests-ip-rotator#66]
is there any way to use this method to selenium for chrome?

**Comment by Ge0rg3** [comment]
Hi @jun3599, please refer to the [FireProx](https://github.com/ustayready/fireprox) project for this, as you can run it as a proxy server for selenium.

Hope this helps

**Comment by jun3599** [comment]
thank you for your kindless. 
I'll refer to your advice with thanks.😀😀
