### ISSUE TITLE
Invalid Permissions - "Could not create region"

### ISSUE THREAD

**Issue by jessusmach** [Ge0rg3/requests-ip-rotator#67]
can somebody help me how to set it up? I already have my credentials from AWS. I logged in with the AWS CLI. but when I try to use it I got the error <Could not created region (some regions require manual enabling) Using 0 endpoints with name......>
I enabled all the regions on my AWS so I don't know what else do to make it work.

**Comment by Ge0rg3** [comment]
Hi @jessusmach, this sounds like a normal permissions issue. Does your user have the Create API Gateway IAM permission?

**Comment by jessusmach** [comment]
Hey thanks for reached back so quickly.
No. How I do that?

**Comment by Ge0rg3** [comment]
In AWS there's a policy named '[AmazonAPIGatewayAdministrator](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2FAmazonAPIGatewayAdministrator)' - make sure this is assigned to the user that you're using in your CLI.

**Comment by jessusmach** [comment]
I can not get it to work yet. I think my problem is in the implementation. I have to login in my python script or something? @Ge0rg3

**Comment by Ge0rg3** [comment]
Either your AWS access key id/secret have to be set in your environment, or you can pass them in the code like:
```py
gateway = ApiGateway("https://www.google.com", access_key_id="ID", access_key_secret="SECRET")
```

Where ID and SECRET are your id/secret pair.

**Comment by Ge0rg3** [comment]
Resolved via email

**Comment by ThomasAlbrt** [comment]
Hi @Ge0rg3!

Do you remember how you solved it? Thanks :)

**Comment by Ge0rg3** [comment]
Hi @ThomasAlbrt, this error is most commonly due to insufficient permissions. Are you sure your access key id/secret pair have permission to create/manage API Gateways in the region?

**Comment by ThomasAlbrt** [comment]
Hi @Ge0rg3, thanks for the reply!

I'm supposed to have an administrator role but will triple check 🧐
