### ISSUE TITLE
Use ApiGateway object 

### ISSUE THREAD

**Issue by deeeeeelan** [Ge0rg3/requests-ip-rotator#69]
Are there any way i can use the ApiGateway object created from my local machine on my Lambda without invoking the gateway.start() method ? reason on Lambda currently its quite slow, i just want to use it without having an error on endpoints, this is my snippet that i tested on my local.

google.com is just a dummy target btw

`
>>> from requests_ip_rotator import ApiGateway
>>> adapter = ApiGateway("https://www.google.com", regions=["us-west-1", "us-west-2"],access_key_id="xxxxx", access_key_secret="xxxxx")
>>> session = requests.Session()
>>> session.mount('https://www.google.com', adapter)
>>> res = session.get("https://www.google.com/blabla")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_ip_rotator/ip_rotator.py", line 56, in send
    endpoint = choice(self.endpoints)
                      ^^^^^^^^^^^^^^
AttributeError: 'ApiGateway' object has no attribute 'endpoints'
`

**Comment by Ge0rg3** [comment]
Hey @deeeeeelan, thanks for the issue.

You can pregenerate your endpoints like:
```py
import json
from requests_ip_rotator import ApiGateway

gateway = ApiGateway("https://site.com")

endpoints = gateway.start()
print(json.dump(endpoints))
```

Then store these endpoints and do not close the gateway.

In your lambda, you can then do:
```py
from requests_ip_rotator import ApiGateway

gateway = ApiGateway("https://site.com")

gateway.start(endpoints=[...])  #replace with your endpoints
```

Then there will be no delay.

Hope this helps

**Comment by deeeeeelan** [comment]
cool @Ge0rg3 , thanks for your prompt reply. its working at the moment, but im still getting kicked with captcha by my target currently haha. still lurking around for a scrape project to bypass this site captcha/protection.

**Comment by Ge0rg3** [comment]
Hahah its tough, feel free to message me privately if you want some help, my email is on https://georgeom.net/
