### ISSUE TITLE
Requests to subdomains

### ISSUE THREAD

**Issue by nzrv** [Ge0rg3/requests-ip-rotator#70]
Hi there! Thanks for a great library!
I have a question or maybe a feature request.
Is it possible to make requests to a website with different subdomains without registering multiple gateways?
https://coolwebsite.com
https://subdomain.coolwebsite.com
https://anothersubdomain.coolwebsite.com
etc…

**Comment by Ge0rg3** [comment]
Hi @nsrv, sadly this isn't possible through the AWS Api Gateway method currently, as far as I know. Would love to be corrected if somebody can find a way : )

**Comment by contrasting** [comment]
Hi @Ge0rg3 , despite you saying it isn't possible, requests made to a subdomain still seem to work when I tried it?

In fact, even if I create a gateway with a completely random domain, e.g. `ApiGateway("https://foo.com")`, requests to another domain `https://bar.com` still seem to go through.

Am I doing something wrong? Is the site passed to the constructor just a label?

Thank you!

**Comment by Ge0rg3** [comment]
Hey @contrasting, yeah the README needs some tweaks -- the first parameter in ApiGateway only needs to be the protocol (either "http://" or "https://"), the rest is redundant.

It's interesting that subdomains are working though, I'll check that
