### ISSUE TITLE
Asyncio Integration / Multi threading ?

### ISSUE THREAD

**Issue by SaadTPTW** [Ge0rg3/requests-ip-rotator#71]
Hello ! 

I just wanna say thanks fro this awesome project.

Can it be possible to add an example in order to treat in an industrial way high frequency requests ( 1 million link to catch)

Stay available if you wanna discuss about this

**Comment by Ge0rg3** [comment]
Hi, thanks for raising the issue.

Please check #6, this project is only for the requests lib but you can achieve concurrency via multithreading - see [here](https://github.com/Ge0rg3/requests-ip-rotator/issues/6#issuecomment-1893258533).

Thanks :)
