### ISSUE TITLE
Request: Add example of how this could be used with selenium

### ISSUE THREAD

**Issue by DeflateAwning** [Ge0rg3/requests-ip-rotator#74]
In the README, there's an example of how to "mount" this to a `requests` session.

I'm curious if there's a way to do the same thing, but with a Selenium driver instance?

**Comment by Ge0rg3** [comment]
Hi @DeflateAwning, your best bet is likely to run a [fireprox](https://github.com/ustayready/fireprox) proxy locally and set selenium to point to that proxy.

Hope this answers your question?

**Comment by Ge0rg3** [comment]
Hi @DeflateAwning, closing this for now. If you have any further questions feel free to reopen.
